/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2018-08-04 19:09:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;

public final class testServlet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Try to hack</title>\n");
      out.write("\t\t<meta HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=ISO-8859-1\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("\t\t\n");
      out.write("\t\t<style>\t\n");
      out.write("\t\t\n");
      out.write("\t\t\tbody{\n");
      out.write("\t\t\t\tbackground-color:#e9e9e9;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\th1{\n");
      out.write("\t\t\t\tcolor:white;\n");
      out.write("\t\t\t\tfont-weight:400;\n");
      out.write("\t\t\t\tmargin-left:5px;\n");
      out.write("\t\t\t\ttext-shadow: 0 1px 4px rgba(0,0,0,1);\n");
      out.write("\t\t\t\tfont-size:22px;\n");
      out.write("\t\t\t\tdisplay:inline;\n");
      out.write("\t\t\t\tmargin:0 auto;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\t.login_wrapper{\n");
      out.write("\t\t\t\tposition:fixed;\n");
      out.write("\t\t\t\ttop:20%;\n");
      out.write("\t\t\t\tleft:10%;\n");
      out.write("\t\t\t\tmargin:0 auto;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.register_btn{\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\ttext-align:center;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.register_btn a{\n");
      out.write("\t\t\t\tcolor:rgb(63, 159, 255);\n");
      out.write("\t\t\t\ttext-decoration:none;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.login_wrapper div{\n");
      out.write("\t\t\t\tbackground-color:white;\n");
      out.write("\t\t\t\tbox-shadow: 0 0 12px 0 rgba(0,0,0,0.1), 0 10px 30px 0 rgba(0,0,0,0.5);\n");
      out.write("\t\t\t\tborder-radius:10px;\n");
      out.write("\t\t\t\tpadding:25px;\n");
      out.write("\t\t\t\twidth:225px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.login_wrapper div h2{\n");
      out.write("\t\t\t\ttext-align:center;\n");
      out.write("\t\t\t\tpadding-bottom:15px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.login_wrapper div p {\n");
      out.write("\t\t\t\tcolor:#6A6D70;\n");
      out.write("\t\t\t\tfont-size:12px;\n");
      out.write("\t\t\t\tmargin:15px 0 5px 0;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.login_wrapper div input{\n");
      out.write("\t\t\t\twidth:100%;\n");
      out.write("\t\t\t\tpadding:10px 10px;\n");
      out.write("\t\t\t\tborder:1px solid #BABCBF;\n");
      out.write("\t\t\t\tborder-radius:5px;\n");
      out.write("\t\t\t\toutline: none;\n");
      out.write("\t\t\t\tbackground-color:white;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.login_wrapper div input:hover, .login_wrapper div input:focus, .login_wrapper div input:active{\n");
      out.write("\t\t\t\tborder:1px solid black;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t#submit_btn:hover{\n");
      out.write("\t\t\t\topacity:0.8;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.copyright{\n");
      out.write("\t\t\t\tposition:fixed;\n");
      out.write("\t\t\t\tright:0;\n");
      out.write("\t\t\t\tleft:0;\n");
      out.write("\t\t\t\tbottom:20px;\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.copyright p {\n");
      out.write("\t\t\t\tcolor: white ; //#6A6D70;\n");
      out.write("\t\t\t\ttext-align:right;\n");
      out.write("\t\t\t\tfont-size:12px;\n");
      out.write("\t\t\t\tmargin:15px 25px 5px 0;\n");
      out.write("\t\t\t\ttext-shadow: 0 1px 4px rgba(0,0,0,0.5);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</style>\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\t<body>\n");
      out.write("\t\t<h1 style=\"position:fixed; left:15px; background-color:black; padding:2px 5px;\">Try to hack</h1>\n");
      out.write("\t\t<h1 style=\"text-align:center; position:fixed; left:0; right:0; top:15px; font-size:16px;\"><i class=\"fa fa-unlock\"></i><span> Version non sécurisé</span></h1>\n");
      out.write("\t\t<h1 style=\"position:fixed; right:15px; top:15px; text-shadow:none; color:black; font-size:14px; padding:2px 5px;\"><a href=\"Accueil\" style=\"text-decoration:none; color:black;\" >Retour à l'accueil</a></h1>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"login_wrapper\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<h2>Sign in as Admin</h2>\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/messageErreur.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t<form ACTION=\"TestServlet\" METHOD=\"POST\">\n");
      out.write("\t\t\t    <p>Username</p>\n");
      out.write("\t\t\t    <input TYPE=\"TEXT\" NAME=\"username\" autofocus>\n");
      out.write("\n");
      out.write("\t\t\t    <p>Password</p>\n");
      out.write("\t\t\t    <input TYPE=\"TEXT\" NAME=\"password\">\n");
      out.write("\n");
      out.write("\t\t\t\t<input id=\"submit_btn\" type=\"submit\" name=\"signin\" value=\"Sign in\" style=\"background-color:black; color:white; border:0; font-size:14px; margin-top:15px;\">\t\t\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"copyright\">\n");
      out.write("\t\t\t<p>©2018 IFT606 - Sécurité & Cryptography. Projet de session.</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
