/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2018-08-04 16:10:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;

public final class accueil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/kevinboisvert/Desktop/UdeS/UdeS%20-%20Session04/IFT606/02-TSession/base_code/TryToHack_APP_SECURED/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1533397979000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Try to hack</title>\r\n");
      out.write("\t\t<meta HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/chat.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/email.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\tbody {margin:0;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.icon-bar {\r\n");
      out.write("\t\t\t    width: 100%;\r\n");
      out.write("\t\t\t    background-color: #555;\r\n");
      out.write("\t\t\t    overflow: auto;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.icon-bar a {\r\n");
      out.write("\t\t\t    float: left;\r\n");
      out.write("\t\t\t    width: 20%;\r\n");
      out.write("\t\t\t    text-align: center;\r\n");
      out.write("\t\t\t    padding: 12px 0;\r\n");
      out.write("\t\t\t    transition: all 0.3s ease;\r\n");
      out.write("\t\t\t    color: white;\r\n");
      out.write("\t\t\t    font-size: 36px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.icon-bar a:hover {\r\n");
      out.write("\t\t\t    background-color:#00b8e6;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t#mainFrame {\r\n");
      out.write("\t\t\t    margin: auto;\r\n");
      out.write("\t\t\t    width: 100%;\r\n");
      out.write("\t\t\t    height: 700px;\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t    padding: 100px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.box1{\r\n");
      out.write("\t\t\t\twidth: 400px;\r\n");
      out.write("\t\t\t    height: 500px;\r\n");
      out.write("\t\t\t    border: 1px solid w3-light-grey;\r\n");
      out.write("\t\t\t    float: left;\r\n");
      out.write("\t\t\t    text-align: center;\r\n");
      out.write("\t\t\t    border-radius: 5px;\r\n");
      out.write("\t\t\t    vertical-align: middle;\r\n");
      out.write("\t\t\t    margin-top: 23px;\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.box2{\r\n");
      out.write("\t\t\t\twidth: 65%;\r\n");
      out.write("\t\t\t    height: 500px;\r\n");
      out.write("\t\t\t    border: 1px solid w3-light-grey;\r\n");
      out.write("\t\t\t    float: right;\r\n");
      out.write("\t\t\t    margin: 0 auto;\r\n");
      out.write("\t\t\t    border-radius: 5px;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.container {\r\n");
      out.write("\t\t\t    border: 2px solid #dedede;\r\n");
      out.write("\t\t\t    background-color: #f1f1f1;\r\n");
      out.write("\t\t\t    border-radius: 5px;\r\n");
      out.write("\t\t\t    padding: 10px;\r\n");
      out.write("\t\t\t    margin: 10px 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.darker {\r\n");
      out.write("\t\t\t    border-color: #ccc;\r\n");
      out.write("\t\t\t    background-color: #ddd;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.container::after {\r\n");
      out.write("\t\t\t    content: \"\";\r\n");
      out.write("\t\t\t    clear: both;\r\n");
      out.write("\t\t\t    display: table;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.container img {\r\n");
      out.write("\t\t\t    float: left;\r\n");
      out.write("\t\t\t    max-width: 60px;\r\n");
      out.write("\t\t\t    width: 100%;\r\n");
      out.write("\t\t\t    margin-right: 20px;\r\n");
      out.write("\t\t\t    border-radius: 50%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.container img.right {\r\n");
      out.write("\t\t\t    float: right;\r\n");
      out.write("\t\t\t    margin-left: 20px;\r\n");
      out.write("\t\t\t    margin-right:0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.time-right {\r\n");
      out.write("\t\t\t    float: right;\r\n");
      out.write("\t\t\t    color: #aaa;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.time-left {\r\n");
      out.write("\t\t\t    float: left;\r\n");
      out.write("\t\t\t    color: #999;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.content {\r\n");
      out.write("\t\t\t\theight: 100%;\r\n");
      out.write("\t\t\t\toverflow: auto;\r\n");
      out.write("\t\t\t\tborder: 1px solid w3-light-grey;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.txtInput {\t\t\t\t\r\n");
      out.write("\t\t\t\tborder: 2px solid #dedede;\r\n");
      out.write("\t\t\t    background-color: #f1f1f1;\r\n");
      out.write("\t\t\t    border-radius: 5px;\r\n");
      out.write("\t\t\t    padding: 10px;\r\n");
      out.write("\t\t\t    margin: 10px 0;\r\n");
      out.write("\t\t\t    width: 100%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.box2{\r\n");
      out.write("\t\t\t\tborder:1px solid #dedede;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body onload=\"startListen();\">\r\n");
      out.write("\t\t<div class=\"icon-bar\">\r\n");
      out.write("\t\t  <a href=\"#\"><i class=\"fa fa-user\"></i></a> \r\n");
      out.write("\t\t  <a href=\"#\"><i class=\"fa fa-search\"></i></a> \r\n");
      out.write("\t\t  <a href=\"#\"><i class=\"fa fa-envelope\"></i></a> \r\n");
      out.write("\t\t  <a href=\"#\"><i class=\"fa fa-address-book\"></i></a>\r\n");
      out.write("\t\t  <a href=\"Logout\"><i class=\"fa fa-sign-out\"></i></a> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"mainFrame\">\r\n");
      out.write("\t\t\t<div class=\"box1\">\r\n");
      out.write("\t\t\t\t<input type=\"file\" name=\"img\" multiple>\r\n");
      out.write("\t\t\t\t<div class=\"sendMessage\">\r\n");
      out.write("\t\t\t\t  <form class=\"w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin\">\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<div class=\"w3-row w3-section\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"w3-col\" style=\"width:50px\"><i class=\"w3-xxlarge fa fa-user\"></i></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"w3-rest\">\r\n");
      out.write("\t\t\t\t\t      <input id=\"emailDest\" class=\"w3-input w3-border\" name=\"first\" type=\"text\" placeholder=\"Email destinataire\">\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-row w3-section\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"w3-col\" style=\"width:50px\"><i class=\"w3-xxlarge fa fa-user\"></i></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"w3-rest\">\r\n");
      out.write("\t\t\t\t\t      <input id=\"emailSender\" class=\"w3-input w3-border\" name=\"last\" type=\"text\" placeholder=\"Gmail emmetteur\">\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-row w3-section\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"w3-col\" style=\"width:50px\"><i class=\"w3-xxlarge fa fa-key\"></i></div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"w3-rest\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"emailSenderPsw\" class=\"w3-input w3-border\" name=\"last\" type=\"password\" placeholder=\"FakePSW\">\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-row w3-section\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"w3-col\" style=\"width:50px\"><i class=\"w3-xxlarge fa fa-pencil-square-o\"></i></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"w3-rest\">\r\n");
      out.write("\t\t\t\t\t      <input placeholder=\"Subject\" id=\"emailSubject\" class=\"w3-input w3-border\" name=\"last\"></textarea>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-row w3-section\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"w3-col\" style=\"width:50px\"><i class=\"w3-xxlarge fa fa-pencil\"></i></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"w3-rest\">\r\n");
      out.write("\t\t\t\t\t      <input id=\"emailMsg\" class=\"w3-input w3-border\" name=\"message\" type=\"text\" placeholder=\"Message\">\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"w3-button w3-block w3-section w3-blue w3-ripple w3-padding\" onclick=\"email.dosendbtn();\" >Send</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box2\">\r\n");
      out.write("\t\t\t\t<h2>Messages</h2>\r\n");
      out.write("\t\t\t\t<div id=\"content\" class=\"content\"></div>\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-top: -50px;\">\r\n");
      out.write("\t\t\t\t\t\t<textarea id=\"txtInput\" class=\"txtInput\" onkeyup=\"dokeyup(event);\" placeholder=\"Message\"></textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input id=\"btnEnvoyer\" type=\"button\" value=\"Envoyer\" onclick=\"sendBtn();\" /> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
